title: Machine Learning for Neuroscience
author: Dr. Shlomi Lifshits, Zvi Baratz
logo: logo.png

repository:
  path_to_book: source/
  url: https://github.com/ZviBaratz/ml_for_neuro

execute:
  timeout: -1

html:
  home_page_in_navbar: true
  use_issues_button: true

launch_buttons:
  binderhub_url: https://mybinder.org

latex:
  latex_documents:
    targetname: book.tex

exclude_patterns: ["*skip.ipynb"]
