title: Machine Learning for Neuroscience
author: Dr. Shlomi Lifshitz, Zvi Baratz
logo: logo.png

repository:
  url: https://github.com/ZviBaratz/ml_for_neuro
  path_to_book: source/

html:
  use_issues_button: true

launch_buttons:
  binderhub_url: https://mybinder.org

latex:
  latex_documents:
    targetname: book.tex
